# Generated by Django 5.2.4 on 2025-07-28 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO 4217 код, например: BYN, USD, EUR', max_length=3, unique=True)),
                ('name', models.CharField(blank=True, help_text='Название валюты на русском', max_length=50)),
                ('symbol', models.CharField(blank=True, help_text='Символ: ₽, $, € и т.д.', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
