# Generated by Django 5.2.4 on 2025-08-03 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный идентификатор для пути')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO заголовок')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Служебная информация',
                'verbose_name_plural': 'Служебная информация',
            },
        ),
    ]
