# Generated by Django 5.2.4 on 2025-08-06 17:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepolicy',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
