# Generated by Django 5.2.4 on 2025-08-04 11:01

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text="Имя URL-шаблона с namespace (например: 'landing:policy_detail') или абсолютная ссылка", max_length=200)),
                ('url_params', models.JSONField(blank=True, help_text="Параметры для reverse(), например: {'slug': 'privacy-policy'}", null=True)),
                ('is_named_url', models.BooleanField(default=True, help_text='True — использовать reverse() по url_name')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='userpanel.profilemenucategory')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню личного кабинета',
            },
        ),
    ]
