# Generated by Django 5.2.4 on 2025-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemenucategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически создаётся из названия. Используется для URL-конфигурации.', max_length=100),
        ),
    ]
