# Generated by Django 5.2.4 on 2025-08-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_profilemenucategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemenucategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически создаётся из названия. Используется для URL-конфигурации.', max_length=100, unique=True),
        ),
    ]
